# Generated by Django 5.2.7 on 2026-01-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationchoice',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='evaluationchoice',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='evaluationchoice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Est correct'),
        ),
        migrations.AlterField(
            model_name='evaluationchoice',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Texte du choix'),
        ),
    ]
