# Generated by Django 5.2.7 on 2026-01-05 00:27

import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('type', models.CharField(choices=[('DM', 'Message direct'), ('GROUP', 'Groupe')], default='DM', max_length=10)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'salle de discussion',
                'verbose_name_plural': 'salles de discussion',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="date d'envoi")),
                ('body', models.TextField(verbose_name='contenu')),
                ('read', models.BooleanField(db_index=True, default=False, verbose_name='lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='date de lecture')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ('-timestamp',),
            },
        ),
    ]
