# Generated by Django 5.2.7 on 2026-01-05 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatroom'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='core_read_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_received_messages', to=settings.AUTH_USER_MODEL, verbose_name='destinataire'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='expéditeur'),
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['user', 'recipient', 'read'], name='core_messag_user_id_440d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['recipient', 'read'], name='core_messag_recipie_8c09af_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['chat', 'timestamp'], name='core_messag_chat_id_02cce6_idx'),
        ),
    ]
