# Generated by Django 5.2.8 on 2025-11-27 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_messagemodel_recipient_alter_messagemodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='lu'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de lecture'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=models.TextField(verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_received_messages', to=settings.AUTH_USER_MODEL, verbose_name='destinataire'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="date d'envoi"),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='expéditeur'),
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['user', 'recipient', 'read'], name='core_messag_user_id_440d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['recipient', 'read'], name='core_messag_recipie_8c09af_idx'),
        ),
    ]
