# Generated by Django 5.2.8 on 2025-12-02 12:32

import django.db.models.deletion
import shortuuidfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_messagemodel_read_messagemodel_read_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='core_read_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_received_messages', to=settings.AUTH_USER_MODEL, verbose_name='destinataire'),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('type', models.CharField(choices=[('DM', 'Message direct'), ('GROUP', 'Groupe')], default='DM', max_length=10)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'salle de discussion',
                'verbose_name_plural': 'salles de discussion',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatroom'),
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['chat', 'timestamp'], name='core_messag_chat_id_02cce6_idx'),
        ),
    ]
