[Interface]
PrivateKey = 8Nd9G832qAwOhu1m2W4DFcCEQhrVPOdusQ2ukY7BMUw=
Address = 10.16.0.1/32, fdcc:ad94:bacf:61a4::cafe:6/128
MTU = 1420
DNS = 1.1.1.1, 2606:4700:4700::1111

[Peer]
PublicKey = kucGJNRlk3FZ7cUDIcWs/s9BQ7ZrAtQZSmRt8mAxgEs=
PresharedKey = EPMbYbq+RUy5VuxmRENJ0tW2hjTJr18obhuSbzmIP7M=
AllowedIPs = 10.16.0.0/21
PersistentKeepalive = 25
Endpoint = etatcivil.cm:51821
