[Interface]
PrivateKey = QL0yuFTMyIwR9Ao8+6R2kW6fpbrbDIQCq3KhtaZ3EVo=
Address = 10.8.0.45/16, fdcc:ad94:bacf:61a4::cafe:55/112
DNS = 10.8.0.16, 2606:4700:4700::1111
MTU = 1420

[Peer]
PublicKey = D/P0nqwZy5TqVbPNcNgefvAy/TJO3tILW6V0UvHYIXE=
PresharedKey = u9ywQRApa8MtTyVXEFxM03FT481zzrl/RcsKZFgpTrM=
AllowedIPs = 10.8.0.44/32, fdcc:ad94:bacf:61a4::cafe:54/128
PersistentKeepalive = 25
Endpoint = etatcivil.cm:51825