# Generated by Django 5.2.7 on 2025-11-15 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('courses', '0006_lessonvideo_courselike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='course',
        ),
        migrations.AddField(
            model_name='classroom',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='courses.category'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='recording_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livesession',
            name='recording_url',
            field=models.URLField(blank=True),
        ),
    ]
