# Generated by Django 5.2.7 on 2025-12-19 13:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='contenu')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'envoi")),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_received_messages', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='expéditeur')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
