# Generated by Django 5.2.7 on 2026-01-05 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='contenu')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'envoi")),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
