# Generated by Django 5.2.7 on 2025-11-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
