# Generated by Django 5.2.7 on 2025-11-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/files/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/'),
        ),
    ]
