# Generated by Django 5.2.7 on 2025-11-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lessonvideo_created_at_lessonvideo_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonvideo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lessonvideo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lessonvideo',
            name='view_count',
        ),
    ]
