# Generated by Django 5.2.8 on 2025-12-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_lessonvideo_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_file',
        ),
    ]
