# Generated by Django 5.2.8 on 2025-12-17 16:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_lesson_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_acquired', models.JSONField(default=dict, help_text='Compétences acquises avec leur niveau')),
                ('learning_goals', models.TextField(blank=True, help_text="Objectifs d'apprentissage de l'utilisateur", null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('time_spent', models.DurationField(default=datetime.timedelta(0), help_text='Temps total passé sur la plateforme')),
                ('completed_courses', models.ManyToManyField(blank=True, related_name='completed_by', to='courses.course')),
                ('current_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_learners', to='courses.course')),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_learners', to='courses.lesson')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
