# Generated by Django 5.2.7 on 2026-01-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_lessonprogress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
